INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('Твердый')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
INSERT INTO binding (name_binding) VALUES ('Мягкий')
INSERT INTO binding (name_binding) VALUES ('С металлическими вставками')
